### ISSUE TITLE
Fails hard on Empty Result Set from Railgun

### ISSUE THREAD

**Issue by pjdufour** [spatialcurrent/coconut#24]
## First...
- [x] I've made sure there are no duplicate issues

## Issue type
- [x] bug report
- [ ] feature request

---
**If this is a bug report** (if not, please remove this section)

## Description

When railgun returns an empty result set, the applications fails hard.

### Expected behavior

Application should show "No Results.  Try another query." alert modal.

### Current behavior

Application whites out.

## Steps to reproduce

Try the "Chinese Food" query on https://coconut.spatialcurrent.io/.

## Additional helpful info/screenshots

---

**If this is a feature request** (if not, please remove this section)

## Proposed Solution

New/Adapted Modal for showing message "No results.  Try another query.".

## Risks/concerns
---

**Comment by sdpeyton** [comment]
https://github.com/spatialcurrent/coconut/pull/25
