### ISSUE TITLE
Update URL with Application State

### ISSUE THREAD

**Issue by pjdufour** [spatialcurrent/coconut#37]
## First...
- [x] I've made sure there are no duplicate issues

## Issue type
- [ ] bug report
- [x] feature request

---
**If this is a feature request** (if not, please remove this section)

## Problem

Url doesn't updated depending on state.

## Proposed Solution

Use history api to update url and location.   Search Query should be part of path.  Location should be part of hash.

https://developer.mozilla.org/en-US/docs/Web/API/History

## Risks/concerns

None
---

**Comment by sdpeyton** [comment]
Also add id for feature if feature is open
