### ISSUE TITLE
Download Button

### ISSUE THREAD

**Issue by pjdufour** [spatialcurrent/coconut#7]
We should have a download buttons to:
- download all features in a service (aka query)
- download the selected features. (maybe more of a "share" button group for this one).

**Comment by pjdufour** [comment]
Will need to create a new GET `/services/{name}/download.{ext}` route that returns with a file name.

https://stackoverflow.com/questions/41938718/how-to-download-files-using-axios

**Comment by pjdufour** [comment]
Download Endpoint now available at: 
```
https://railgun.spatialcurrent.io/services/{service_name}/download.{ext}
```

**Comment by sdpeyton** [comment]
See https://github.com/spatialcurrent/coconut/pull/26
